project:
  type: book
  output-dir: docs

execute:
  freeze: auto

book:
  title: "Pharmacie Hospitalière - Atlas des Ressources Essentielles"
  favicon: images/favicon.ico
  author:
    - name: Marvin JACQUET
      orcid: 0000-0002-9890-7908
      url: https://marvinjacquet.github.io/
  date: last-modified
  date-format: "DD MMMM YYYY"
  doi: 10.5281/zenodo.20612426
  repo-branch: main
  repo-url: https://github.com/marvinjacquet/phare
  repo-actions: [issue]
  language: fr

  sidebar:
    logo: images/phare.svg
    search: true
    location: left
    style: "docked"
    background: light

  chapters:
    - index.qmd
    - part: "**Par spécialité**"
      chapters:
        - interactions.qmd
        - adaptation.qmd
        - iatrogenie.qmd
        - compatibilite.qmd
    - part: "**Par type**"
      chapters:
        - index-outils.qmd
        - recommandations.qmd
        - etp.qmd
        - pharmacologie.qmd
        - conversions.qmd
        - ruptures.qmd

format:
  html:
    theme:
      light: cosmo
      dark: darkly
    engine: knitr
    toc: true
    toc-depth: 3
    toc-title: "Sur cette page"
    number-sections: false
    smooth-scroll: true
    lang: fr
    css: styles.css
    grid:
      sidebar-width: 280px
      body-width: 900px
      margin-width: 200px
