project:
  type: book
  output-dir: docs

execute:
  freeze: auto

book:
  title: "Pharmacie Hospitalière - Atlas des Ressources Essentielles"
  favicon: images/favicon.ico
  author:
    - name: Marvin JACQUET
      orcid: 0000-0002-9890-7908
      url: https://marvinjacquet.github.io/
  date: last-modified
  date-format: "DD MMMM YYYY"
  doi: 10.5281/zenodo.20612426
  repo-branch: main
  repo-url: https://github.com/marvinjacquet/phare
  repo-actions: [issue]
  language: fr

  sidebar:
    logo: images/phare.svg
    search: true
    location: left
    style: "docked"
    background: light

  chapters:
    - index.qmd
    - part: "**Outils**"
      chapters: 
        - index-outils.qmd
        - outils/referentiels.qmd
        - outils/interactions.qmd
        - outils/iatrogenie.qmd
        - outils/adaptation.qmd
        - outils/compatibilite.qmd
        - outils/deprescription.qmd
        - outils/education.qmd
        - outils/formation.qmd
        - outils/calculs.qmd
        - outils/disponibilite.qmd
        - outils/autre.qmd
    - part: "**Recommandations**"
      chapters: 
        - index-recommandations.qmd
        - recommandations/general.qmd
        - recommandations/cardiologie.qmd
        - recommandations/diabetologie.qmd
        - recommandations/geriatrie.qmd
        - recommandations/hematologie.qmd
        - recommandations/hepatologie.qmd
        - recommandations/infectiologie.qmd
        - recommandations/nephrologie.qmd
        - recommandations/oncologie.qmd
        - recommandations/pediatrie.qmd
        - recommandations/pneumologie.qmd
        - recommandations/psychiatrie.qmd
        - recommandations/soinspal.qmd
        - recommandations/urgences.qmd

format:
  html:
    theme:
      light: cosmo
      dark: darkly
    engine: knitr
    toc: true
    toc-depth: 3
    toc-title: "Sur cette page"
    number-sections: false
    smooth-scroll: true
    lang: fr
    css: styles.css
    grid:
      sidebar-width: 280px
      body-width: 900px
      margin-width: 200px
